include ./nord.conf

# Fonts
# font_family      Lilex Nerd Font Mono
font_family	 SarasaTermSCNerd
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 16.0
background_opacity 0.80

padding 12.0
